
import java.text.DecimalFormat;

/*
 This is a program that calculates the GPA for a student going into the IS program.
The user inputs all the credits and grades recieved, and then the program does a simple
GPA calculation and then outputs the GPA on the left, with a color of the possibility of them 
getting into the program. Green is good, yellow is kind of good, and then red is a unlikely chance. 
 */

/**
 *
 * @author Kory Hutchison Section 1
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtBusm241 = new javax.swing.JTextField();
        txt110 = new javax.swing.JTextField();
        txt201 = new javax.swing.JTextField();
        txt303 = new javax.swing.JTextField();
        txtAcc200 = new javax.swing.JTextField();
        txtFin201 = new javax.swing.JTextField();
        cmbBusm241 = new javax.swing.JComboBox<>();
        cmb110 = new javax.swing.JComboBox<>();
        cmb201 = new javax.swing.JComboBox<>();
        cmb303 = new javax.swing.JComboBox<>();
        cmbAcc200 = new javax.swing.JComboBox<>();
        cmbFin201 = new javax.swing.JComboBox<>();
        btnCalcGpa = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblGpa = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panRed = new javax.swing.JPanel();
        panGreen = new javax.swing.JPanel();
        panYellow = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IS Pre-req GPA Calculator");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Your Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 130));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Credits");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Grade");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Course");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel7.setText("BUSM 241");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel8.setText("IS 110");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel9.setText("IS 201");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel10.setText("IS 303");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel11.setText("ACC 200");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel12.setText("FIN 201");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        txtBusm241.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txtBusm241.setText("3");
        jPanel2.add(txtBusm241, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 30, -1));

        txt110.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txt110.setText("1");
        txt110.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt110PropertyChange(evt);
            }
        });
        jPanel2.add(txt110, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 30, -1));

        txt201.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txt201.setText("3");
        jPanel2.add(txt201, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 30, -1));

        txt303.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txt303.setText("3");
        jPanel2.add(txt303, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 30, -1));

        txtAcc200.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txtAcc200.setText("3");
        jPanel2.add(txtAcc200, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 30, -1));

        txtFin201.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txtFin201.setText("3");
        jPanel2.add(txtFin201, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 30, -1));

        cmbBusm241.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        cmbBusm241.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        jPanel2.add(cmbBusm241, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 60, -1));

        cmb110.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        cmb110.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        jPanel2.add(cmb110, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 60, -1));

        cmb201.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        cmb201.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        jPanel2.add(cmb201, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 60, -1));

        cmb303.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        cmb303.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        jPanel2.add(cmb303, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 60, -1));

        cmbAcc200.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        cmbAcc200.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        jPanel2.add(cmbAcc200, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 60, -1));

        cmbFin201.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        cmbFin201.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        jPanel2.add(cmbFin201, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 60, -1));

        btnCalcGpa.setText("Calc GPA");
        btnCalcGpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcGpaMouseClicked(evt);
            }
        });
        jPanel2.add(btnCalcGpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        btnReset.setText("Reset");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        jPanel2.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Enter Grades");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 280, 380));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGpa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(lblGpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 50, 20));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("GPA");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        panRed.setBackground(new java.awt.Color(255, 0, 0));
        panRed.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                panRedPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout panRedLayout = new javax.swing.GroupLayout(panRed);
        panRed.setLayout(panRedLayout);
        panRedLayout.setHorizontalGroup(
            panRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        panRedLayout.setVerticalGroup(
            panRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(panRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 60, 50));

        panGreen.setBackground(new java.awt.Color(0, 255, 0));
        panGreen.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                panGreenPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout panGreenLayout = new javax.swing.GroupLayout(panGreen);
        panGreen.setLayout(panGreenLayout);
        panGreenLayout.setHorizontalGroup(
            panGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        panGreenLayout.setVerticalGroup(
            panGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(panGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 60, 50));

        panYellow.setBackground(new java.awt.Color(255, 255, 51));
        panYellow.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                panYellowPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout panYellowLayout = new javax.swing.GroupLayout(panYellow);
        panYellow.setLayout(panYellowLayout);
        panYellowLayout.setHorizontalGroup(
            panYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        panYellowLayout.setVerticalGroup(
            panYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(panYellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 60, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 230, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt110PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt110PropertyChange
        
    }//GEN-LAST:event_txt110PropertyChange

    private void btnCalcGpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcGpaMouseClicked
        //Declare Variables
        double dTotalCredits;
        double dGpa;
        DecimalFormat dFormat = new DecimalFormat("0.00");
        
        
        //This adds up all the credits from each text box.
        dTotalCredits = Double.parseDouble(txt110.getText()) + Double.parseDouble(txt201.getText()) + Double.parseDouble(txt303.getText()) + 
                Double.parseDouble(txtAcc200.getText()) + Double.parseDouble(txtFin201.getText()) + Double.parseDouble(txtBusm241.getText());
        
        //This is the final gpa by passing all the information into the calcGpa method and then dividing it by the number of credits.
        dGpa = (calcGpa(cmb110.getSelectedItem().toString(), Double.parseDouble(txt110.getText())) + calcGpa(cmb201.getSelectedItem().toString(), Double.parseDouble(txt201.getText())) +
                calcGpa(cmb303.getSelectedItem().toString(), Double.parseDouble(txt303.getText())) + calcGpa(cmbAcc200.getSelectedItem().toString(), Double.parseDouble(txtAcc200.getText()))
                + calcGpa(cmbFin201.getSelectedItem().toString(), Double.parseDouble(txtFin201.getText())) + calcGpa(cmbBusm241.getSelectedItem().toString(), Double.parseDouble(txtBusm241.getText()))) / dTotalCredits;
        
        lblGpa.setText(String.valueOf(dFormat.format(dGpa)));
        
        //this if statement decides which color shows.
        if(dGpa >= 3.7)
        {
            panGreen.setVisible(true);
        }
        else if(dGpa >= 3.2)
        {
            panYellow.setVisible(true);
        }
        else
        {
            panRed.setVisible(true);
        }
        
    }//GEN-LAST:event_btnCalcGpaMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        //This resets everything by clicking the reset button.
        cmb110.setSelectedIndex(0);
        cmb201.setSelectedIndex(0);
        cmb303.setSelectedIndex(0);
        cmbAcc200.setSelectedIndex(0);
        cmbFin201.setSelectedIndex(0);
        cmbBusm241.setSelectedIndex(0);
        
        lblGpa.setText("0.00");
        
        txtUserName.setText(null);
        
        panGreen.setVisible(false);
        panYellow.setVisible(false);
        panRed.setVisible(false);
        
        txtUserName.requestFocus();
    }//GEN-LAST:event_btnResetMouseClicked

    private void panGreenPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_panGreenPropertyChange
        panGreen.setVisible(false);
    }//GEN-LAST:event_panGreenPropertyChange

    private void panYellowPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_panYellowPropertyChange
        panYellow.setVisible(false);
    }//GEN-LAST:event_panYellowPropertyChange

    private void panRedPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_panRedPropertyChange
        panRed.setVisible(false);
    }//GEN-LAST:event_panRedPropertyChange
    //The calcGpa method. It takes the letter grade, and then 
    private double calcGpa(String sLetterGrade, double dCredit)
    {
        double dGrade = 0;
        //This determines the grade score for the grade in the combo box
        if(sLetterGrade.equalsIgnoreCase("A"))
            {
                dGrade = 4;
            }
            else if(sLetterGrade.equalsIgnoreCase("A-"))
            {
                dGrade = 3.7;
            }
            else if(sLetterGrade.equalsIgnoreCase("B+"))
            {
                dGrade = 3.4;
            }
            else if(sLetterGrade.equalsIgnoreCase("B"))
            {
                dGrade = 3;
            }
            else if(sLetterGrade.equalsIgnoreCase("B-"))
            {
                dGrade = 2.7;
            }
            else if(sLetterGrade.equalsIgnoreCase("C+"))
            {
                dGrade = 2.4;
            }
            else if(sLetterGrade.equalsIgnoreCase("C"))
            {
                dGrade = 2;
            }
            else if(sLetterGrade.equalsIgnoreCase("C-"))
            {
                dGrade = 1.7;
            }
            else if(sLetterGrade.equalsIgnoreCase("D+"))
            {
                dGrade = 1.4;
            }
            else if(sLetterGrade.equalsIgnoreCase("D"))
            {
                dGrade = 1;
            }
            else if(sLetterGrade.equalsIgnoreCase("D-"))
            {
                dGrade = .7;
            }
            else if(sLetterGrade.equalsIgnoreCase("E"))
            {
                dGrade = 0;
            }
        //This then returns the credits multiplied by the leter grade. This will then be divided by the total credits.
        return dCredit * dGrade;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcGpa;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cmb110;
    private javax.swing.JComboBox<String> cmb201;
    private javax.swing.JComboBox<String> cmb303;
    private javax.swing.JComboBox<String> cmbAcc200;
    private javax.swing.JComboBox<String> cmbBusm241;
    private javax.swing.JComboBox<String> cmbFin201;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblGpa;
    private javax.swing.JPanel panGreen;
    private javax.swing.JPanel panRed;
    private javax.swing.JPanel panYellow;
    private javax.swing.JTextField txt110;
    private javax.swing.JTextField txt201;
    private javax.swing.JTextField txt303;
    private javax.swing.JTextField txtAcc200;
    private javax.swing.JTextField txtBusm241;
    private javax.swing.JTextField txtFin201;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
